config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "animals#index"

  resources :animals do
    resources :comments
    collection do
      get 'search'
    end
  end
  resources :users
  resources :messages
  resources :rooms
  resources :calendars
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :rooms

  validates :name, presence: true
  validates :image, presence: true
  validates :genre, presence: true
  validates :gender, presence: true
  validates :birthday, presence: true
  validates :age, presence: true
  validates :prefecture, presence: true
  validates :charm_point, presence: true

  def self.search(search)
    if search != ""
      Animal.where('name LIKE(?)', "%#{search}%")
        .or(Animal.where('genre LIKE(?)', "%#{search}%"))
        .or(Animal.where('gender LIKE(?)', "%#{search}%"))
        .or(Animal.where('birthday LIKE(?)', "%#{search}%"))
        .or(Animal.where('age LIKE(?)', "%#{search}%"))
        .or(Animal.where('prefecture LIKE(?)', "%#{search}%"))
        .or(Animal.where('charm_point LIKE(?)', "%#{search}%"))  
        .or(Animal.where('user_id LIKE(?)', "%#{search}%"))  
    else
      Animal.all
    end
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_animal, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @animals = Animal.includes(:user).order("created_at DESC")
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @animal.comments.includes(:user)
  end

  def search
    @animals = Animal.search(params[:keyword]) 
  end
  

  def edit
    @animal = Animal.find(params[:id])
  end 

  def update
    if @animal.update(animal_params)
       redirect_to animal_path  
    else
      render :edit
    end
  end

  def destroy
    if @animal.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end



  private

  def animal_params
    params.require(:animal).permit(:name, :charm_point, :genre, :gender, :birthday, :age, :prefecture, :image).merge(user_id: current_user.id)
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.html.erb
<div class="card">
  <%= link_to image_tag(animal.image, class: :card__img ), animal_path(animal.id)%>
  <div class="card__body">
    <%= link_to animal.name, animal_path(animal.id), class: :card__title%>
    <p class="card__summary">
      <%= animal.charm_point %>
    </p>
    <%= link_to "By #{animal.user.nickname}", user_path(animal.user_id), class: :card__user %>
  </div>
</div>

app/views/animals/_form.html.erb
<%= form_with model: animal, local: true do |f|%>
  <div class="field">
    <%= f.label :name, "お名前" %><br />
    <%= f.text_field :name, id:"animal_name" %>
  </div>

  <div class="field">
    <%= f.label :genre, "動物の種類" %><br />
    <%= f.text_field :genre,  id:"animal_genre" %>
  </div>

  <div class="field">
    <%= f.label :gender, "性別" %><br />
    <%= f.text_field :gender,  id:"animal_gender" %>
  </div>

  <div class="field">
    <%= f.label :birthday, "お誕生日" %><br />
    <%= f.text_field :birthday,  id:"animal_birthday" %>
  </div>

  <div class="field">
    <%= f.label :age, "年齢" %><br />
    <%= f.text_field :age, id:"animal_age" %>
  </div>

  <div class="field">
    <%= f.label :prefecture, "お住まい" %><br />
    <%= f.text_field :prefecture, class: :form__text, id:"animal_prefecture" %>
  </div>

  <div class="field">
    <%= f.label :charm_point, "チャームポイント" %><br />
    <%= f.text_area :charm_point, class: :form__text, id:"animal_charm_point" %>
  </div>

  <div class="field">
    <%= f.label :image, "動物の画像" %><br />
    <%= f.file_field :image, id:"animal_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/animals/_side_bar.html.erb
<div class="side-bar">
  <div class="side-contents">
    <div class="side-content">
      <% if user_signed_in? %>
        <%= link_to "マイページ", "/users/#{current_user.id}", class: :new_animal %>
      <% else %>
      <%= link_to "マイページ", "/users/index", class: :new_animal %>
      <% end %>
    </div>
    <div class="side-content">
      <%= link_to "記事を投稿する", new_animal_path, class: :new_animal %>
    </div>
    <div class="side-content">
      <%= link_to "ユーザ一覧", users_path, class: :new_animal %>
    </div>

    <div class="side-content">
      <%= link_to "イベント一覧", calendars_path, class: :new_animal %>
    </div>
  </div>
</div>
 

app/views/animals/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿記事編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { animal: @animal } %>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<main class="main">
<div class="wrapper">
    <%= render partial: "side_bar" %>
  <div class="body">
  <div class="inner">
      <%# ログインしているときは以下を表示する %>
      <% if user_signed_in? %>
       <div class="greeting">
        <%= link_to "#{current_user.nickname} さんとしてログイン中です", "/users/#{current_user.id}", class: :greeting__link%>
      </div>
      <% end %>

      <%= form_with(url: search_animals_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワードで検索", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
        <%# // ログインしているときは上記を表示する %>
      <div class="card__wrapper">
        <%# 部分テンプレートでプロトタイプ投稿一覧を表示する %>
       <%# @animals.each do |animal| %>
       <%= render partial: "animal", collection: @animals %>
       <%# end %>
      </div>
    </div>
  </div>
</main>

app/views/animals/new.html.erb
<main class="main">
<div class="wrapper">
    <%= render partial: "side_bar" %>
    

<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { animal: @animal } %>
    </div>
  </div>
</div>
</div>
</main>

app/views/animals/search.html.erb
 <div class="animal__wrapper">
       

<main class="main">
  <div class="wrapper">
      <%= render partial: "side_bar" %>
      <div class="search-results">
        <div class="search-header">
       <%= link_to '<<TOPへ戻る', root_path,  class: :top_btn %>
      <%= form_with(url: search_animals_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "キーワードで検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
      </div>
      
      

        <div class="search-result">
          <%= "検索結果:" %>

          <div class="contents-row">
           <% @animals.each do |animal| %>
             <%= render partial: "animal", locals: { animal: animal } %>
           <% end %>
         </div>
       </div>
      
  </div>
</main>

app/views/animals/show.html.erb
<main class="main">
<div class="wrapper">
  <div class="side-bar">
  <div class="side-contents">
    <div class="side-content">
      <% if user_signed_in? %>
      <%= link_to "マイページ", "/users/#{current_user.id}", class: :new_animal %>
      <% else %>

      <%= link_to "マイページ", "/users/index", class: :new_animal %>
      <% end %>
    </div>
    <div class="side-content">
      <%= link_to "記事を投稿する", new_animal_path, class: :new_animal %>
    </div>
    <div class="side-content">
      <%= link_to "ユーザ一覧", users_path, class: :new_animal %>
    </div>
    <div class="side-content">
      <%= link_to "イベント一覧", calendars_path, class: :new_animal %>
    </div>
  </div>
</div>
  <div class="body">
  <div class="inner">
    <div class="animal__wrapper">
    <%= link_to '<<TOPへ戻る', root_path,  class: :top_btn %>
    
      <p class="animal__hedding">
        <%= @animal.name %>
      </p>
      <%= link_to "by #{@animal.user.nickname}", user_path(@animal.user), class: :animal__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @animal.user_id %>
        <div class="animal__manage">
          <%= link_to "編集する", edit_animal_path(@animal), class: :animal__btn %>
          <%= link_to "削除する", animal_path(@animal), method: :delete, class: :animal__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="animal_show">
      <div class="detail_left">
        <div class="animal__image">
          <%= image_tag @animal.image %>
        </div>
      </div>
      <div class="detail_right">
      <div class="animal__body">
        <div class="animal__detail">
          <p class="detail__title">種類</p>
          <p class="detail__message">
            <%= @animal.genre %>
          </p>
          <p class="detail__title">性別</p>
          <p class="detail__message">
            <%= @animal.gender %>
          </p>
          <p class="detail__title">お誕生日</p>
          <p class="detail__message">
            <%= @animal.birthday %>
          </p>
          <p class="detail__title">年齢</p>
          <p class="detail__message">
            <%= @animal.age %>
          </p>
          <p class="detail__title">お住まい</p>
          <p class="detail__message">
            <%= @animal.prefecture %>
          </p>
          <p class="detail__title">チャームポイント</p>
          <p class="detail__message">
            <%= @animal.charm_point %>
          </p>
        </div>
      </div>
    </div>
   </div>
      
      <%# コメント機能 %>
      <div class="animal__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@animal, @comment],local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
             <li class="comments_list"> 
               <%= comment.text %>
               <%= link_to "(#{comment.user.nickname})", user_path(comment.user), class: :comment_user %> 
             </li> 
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>